const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=v=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let products=[],cart=JSON.parse(localStorage.getItem('sf88_cart')||'[]');
async function load(){const r=await fetch('data/products.json?v=88.2',{cache:'no-store'});products=(await r.json()).products||[];return products}
function header(){const n=cart.reduce((a,b)=>a+b.qty,0);$('#header').innerHTML=`<div class="utility">BRANDED STOCK · FOUND DIFFERENTLY · EST. 1988</div><header class="header"><div class="head"><button class="menu" id="menuBtn" aria-label="Open menu">☰</button><a class="logo" href="index.html">STOCK &amp;<br>FOUND <small>88 · EST. 1988</small></a><nav class="nav"><a href="shop.html">NEW DROP</a><a href="shop.html?cat=Men">MEN</a><a href="shop.html?cat=Women">WOMEN</a><a href="shop.html?cat=Kids">KIDS</a><a href="shop.html?cat=Shoes">SHOES</a><a href="shop.html?cat=Accessories">ACCESSORIES</a></nav><div class="actions"><a href="shop.html">SHOP</a><button id="bagBtn">BAG <span id="count">${n||''}</span></button></div></div></header>`;$('#menuBtn').onclick=()=>{let m=$('#mobileMenu');if(!m){m=document.createElement('div');m.id='mobileMenu';m.className='mobile-menu';m.innerHTML=`<div class="mobile-menu-top"><span>STOCK &amp; FOUND 88</span><button id="closeMobile">CLOSE ×</button></div><a href="shop.html">NEW DROP ↗</a><a href="shop.html?cat=Men">MEN ↗</a><a href="shop.html?cat=Women">WOMEN ↗</a><a href="shop.html?cat=Kids">KIDS ↗</a><a href="shop.html?cat=Shoes">SHOES ↗</a><a href="shop.html?cat=Accessories">ACCESSORIES ↗</a>`;document.body.appendChild(m);$('#closeMobile').onclick=()=>m.remove()}m.classList.add('open');document.body.classList.add('lock')}}
function footer(){$('#footer').innerHTML=`<footer class="foot"><div class="footgrid"><div><div class="footbrand">STOCK &amp;<br>FOUND 88</div><p>BRANDED STOCK.<br>FOUND DIFFERENTLY.</p></div><div><small>EXPLORE</small><a href="shop.html">New Drop</a><a href="shop.html?cat=Men">Men</a><a href="shop.html?cat=Women">Women</a><a href="shop.html?cat=Kids">Kids</a><a href="shop.html?cat=Shoes">Shoes</a><a href="shop.html?cat=Accessories">Accessories</a></div><div><small>THE STORY</small><p>From the market to your wardrobe.<br>Finding great stock since 1988.</p><a class="footpowered" href="https://mediabay.it" target="_blank" rel="noopener">Powered by MediaBay.it ↗</a></div></div><div class="footbottom"><span>© ${new Date().getFullYear()} STOCK &amp; FOUND 88</span><span>EST. 1988 · ITALY</span><span>BRANDED STOCK / LIMITED PIECES</span></div></footer>`}
function card(p){return `<a class="card" href="product.html?id=${encodeURIComponent(p.id)}"><div class="media"><img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy"><span class="badge">${esc(p.badge||'SELECTED')}</span></div><div class="meta"><small>${esc(p.brand)} · ${esc(p.category)}</small><strong>${esc(p.name)}</strong><span>${p.compareAt?`<del>${money(p.compareAt)}</del>`:''}${money(p.price)}</span></div></a>`}
function renderHome(){const grid=$('#featured');if(grid){const list=products.slice(0,4);grid.innerHTML=list.map(card).join('');$('#featuredCount').textContent=`${String(list.length).padStart(2,'0')} PIECES / CURATED`}}
function renderShop(){let list=products;const cat=new URLSearchParams(location.search).get('cat')||'';if(cat)list=list.filter(p=>p.category===cat);const grid=$('#products');if(grid)grid.innerHTML=list.map(card).join('');if($('#resultCount'))$('#resultCount').textContent=`${String(list.length).padStart(2,'0')} PIECES`;if($('#activeLabel'))$('#activeLabel').textContent=cat?cat.toUpperCase()+' STOCK':'ALL STOCK';$$('.filter').forEach(b=>{b.classList.toggle('active',b.dataset.cat===cat);b.onclick=()=>location.href=b.dataset.cat?'shop.html?cat='+encodeURIComponent(b.dataset.cat):'shop.html'})}
function renderProduct(){const id=new URLSearchParams(location.search).get('id'),p=products.find(x=>x.id===id)||products[0];if(!p||!$('#product'))return;document.title=`${p.name} — STOCK & FOUND 88`;$('#product').innerHTML=`<div class="product-image"><img src="${esc(p.image)}" alt="${esc(p.name)}"></div><div class="product-info"><div class="eyebrow">${esc(p.brand)} · ${esc(p.category)} · ${esc(p.id)}</div><h1>${esc(p.name)}</h1><div class="price">${money(p.price)} ${p.compareAt?`<del>${money(p.compareAt)}</del>`:''}</div><p>${esc(p.description)}</p><div class="eyebrow">SELECT SIZE</div><div class="sizes">${p.sizes.map((s,i)=>`<button class="size ${i===0?'active':''}" data-size="${esc(s)}">${esc(s)}</button>`).join('')}</div><button class="add" id="add">ADD TO BAG ↗</button><div class="note">LIMITED STOCK / DEMO INVENTORY<br>Real brand data, stock levels, photography and order handling will be connected before commercial launch.</div></div>`;$$('.size').forEach(b=>b.onclick=()=>{$$('.size').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$('#add').onclick=()=>{const size=$('.size.active')?.dataset.size||p.sizes[0];const x=cart.find(x=>x.id===p.id&&x.size===size);x?x.qty++:cart.push({id:p.id,size,qty:1});saveCart();openCart()}}
function saveCart(){localStorage.setItem('sf88_cart',JSON.stringify(cart));if($('#count'))$('#count').textContent=cart.reduce((a,b)=>a+b.qty,0)||'';renderCart()}
function renderCart(){const box=$('#cart');if(!box)return;const total=cart.reduce((t,x)=>t+(products.find(p=>p.id===x.id)?.price||0)*x.qty,0);box.innerHTML=`<div class="carttop"><span>YOUR BAG</span><button onclick="closeCart()">CLOSE ×</button></div><div class="cartlist">${cart.length?cart.map((x,i)=>{const p=products.find(p=>p.id===x.id);return p?`<div class="cartitem"><img src="${esc(p.image)}" alt=""><div><small>${esc(p.brand)}</small><strong>${esc(p.name)}</strong><span>${esc(x.size)} · ${x.qty} × ${money(p.price)}</span><button style="margin-top:10px;border:0;background:none;padding:0;font:8px 'DM Mono';cursor:pointer" onclick="removeItem(${i})">REMOVE</button></div></div>`:''}).join(''):'<p style="font:9px \'DM Mono\';color:#777">YOUR BAG IS EMPTY.</p>'}</div><div class="cartbottom"><div class="carttotal"><span>SUBTOTAL</span><strong>${money(total)}</strong></div><a class="btn dark" href="checkout.html">CHECKOUT ↗</a></div>`}
function removeItem(i){cart.splice(i,1);saveCart()}
function openCart(){renderCart();$('#overlay').classList.add('open');$('#cart').classList.add('open');document.body.classList.add('lock')}function closeCart(){$('#overlay').classList.remove('open');$('#cart').classList.remove('open');document.body.classList.remove('lock')}
window.openCart=openCart;window.closeCart=closeCart;window.removeItem=removeItem;
document.addEventListener('DOMContentLoaded',async()=>{header();footer();$('#bagBtn').onclick=openCart;await load();renderCart();if($('#featured'))renderHome();if($('#products'))renderShop();if($('#product'))renderProduct();const form=$('#checkoutForm');if(form)form.onsubmit=e=>{e.preventDefault();form.innerHTML='<div class="eyebrow">REQUEST RECEIVED</div><h2 style="font-size:52px;line-height:.8;letter-spacing:-.07em">WE\'LL<br>GET BACK<br>TO YOU.</h2><p style="color:#77736d">Demo request registrata. Nessun pagamento è stato effettuato.</p>';cart=[];saveCart()}});
