const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=v=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let products=[],cart=JSON.parse(localStorage.getItem('sf88_cart')||'[]');
async function load(){const r=await fetch('data/products.json?v=88.10',{cache:'no-store'});if(!r.ok)throw Error('catalog');products=(await r.json()).products||[]}
function persist(){localStorage.setItem('sf88_cart',JSON.stringify(cart));renderCart();updateCount()}
function updateCount(){if($('#count'))$('#count').textContent=cart.reduce((n,x)=>n+x.qty,0)||''}
function openCart(){$('#overlay')?.classList.add('open');$('#cart')?.classList.add('open');document.body.classList.add('lock');renderCart()}
function closeCart(){$('#overlay')?.classList.remove('open');$('#cart')?.classList.remove('open');document.body.classList.remove('lock')}
window.openCart=openCart;window.closeCart=closeCart;
function mountHeader(){const n=cart.reduce((a,x)=>a+x.qty,0);$('#header').innerHTML=`<div class="utility">BRANDED STOCK · FOUND DIFFERENTLY · EST. 1988</div><header class="header"><div class="head"><button class="menu" id="menuBtn" type="button">☰</button><a class="logo" href="index.html">STOCK &amp;<br>FOUND <small>88 · EST. 1988</small></a><nav class="nav"><a href="shop.html">THE HUNT</a><a href="shop.html?badge=NEW%20FIND">JUST FOUND</a><a href="shop.html?badge=LAST%20PIECE">ALMOST GONE</a><a href="shop.html?cat=Men">MEN</a><a href="shop.html?cat=Women">WOMEN</a><a href="shop.html?cat=Kids">KIDS</a><a href="shop.html?cat=Shoes">SHOES</a><a href="finder.html">FINDER</a></nav><div class="actions"><button id="searchBtn" type="button">SEARCH</button><button id="bagBtn" type="button">BAG <span id="count">${n||''}</span></button></div></div></header><div id="searchPanel" class="search-panel"><div class="search-inner"><input id="globalSearch" type="search" placeholder="Cerca brand, prodotto, categoria..."><button id="closeSearch" type="button">CLOSE ×</button></div><div id="searchResults" class="search-results"></div></div>`;
$('#bagBtn').onclick=openCart;$('#searchBtn').onclick=()=>{$('#searchPanel').classList.add('open');document.body.classList.add('lock');$('#globalSearch').focus()};$('#closeSearch').onclick=()=>{$('#searchPanel').classList.remove('open');document.body.classList.remove('lock')};$('#globalSearch').oninput=e=>search(e.target.value);$('#menuBtn').onclick=toggleMenu}
function toggleMenu(){let m=$('#mobileMenu');if(!m){m=document.createElement('div');m.id='mobileMenu';m.className='mobile-menu';m.innerHTML='<div class="mobile-menu-top"><span>STOCK &amp; FOUND 88</span><button type="button">CLOSE ×</button></div><a href="index.html">HOME ↗</a><a href="shop.html">THE HUNT ↗</a><a href="shop.html?badge=NEW%20FIND">JUST FOUND ↗</a><a href="shop.html?badge=LAST%20PIECE">ALMOST GONE ↗</a><a href="shop.html?cat=Men">MEN ↗</a><a href="shop.html?cat=Women">WOMEN ↗</a><a href="shop.html?cat=Kids">KIDS ↗</a><a href="shop.html?cat=Shoes">SHOES ↗</a><a href="shop.html?cat=Accessories">ACCESSORIES ↗</a><a href="finder.html">FINDER ↗</a>';document.body.appendChild(m);m.querySelector('button').onclick=()=>{m.classList.remove('open');document.body.classList.remove('lock')};m.querySelectorAll('a').forEach(a=>a.onclick=()=>{m.classList.remove('open');document.body.classList.remove('lock')})}m.classList.toggle('open');document.body.classList.toggle('lock',m.classList.contains('open'))}
function mountFooter(){$('#footer').innerHTML=`<footer class="foot"><div class="footgrid"><div><div class="footbrand">STOCK &amp;<br>FOUND 88</div><p>WE GO LOOKING.<br>YOU FIND.</p></div><div><small>EXPLORE</small><a href="shop.html">The Hunt</a><a href="shop.html?badge=NEW%20FIND">Just Found</a><a href="shop.html?badge=LAST%20PIECE">Almost Gone</a><a href="finder.html">Finder</a></div><div><small>THE STORY</small><p>Dal mercato al tuo guardaroba.<br>Scoviamo dal 1988.</p><a href="https://mediabay.it" target="_blank">Powered by MediaBay.it ↗</a></div></div><div class="footbottom"><span>© ${new Date().getFullYear()} STOCK &amp; FOUND 88</span><span>EST. 1988 · ITALY</span><span>BRANDED STOCK / LIMITED PIECES</span></div></footer>`}
function card(p){return `<a class="card" href="product.html?id=${encodeURIComponent(p.id)}"><div class="media"><img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy"><span class="badge">${esc(p.badge)}</span></div><div class="meta"><small>${esc(p.brand)} · ${esc(p.category)}</small><strong>${esc(p.name)}</strong><span>${p.compareAt?'<del>'+money(p.compareAt)+'</del>':''}${money(p.price)}</span></div></a>`}
function search(q){const b=$('#searchResults'),t=q.trim().toLowerCase();if(!t){b.innerHTML='<p>SEARCH THE FIND.</p>';return}const l=products.filter(p=>[p.name,p.brand,p.category,p.id].join(' ').toLowerCase().includes(t)).slice(0,8);b.innerHTML=l.length?l.map(p=>`<a href="product.html?id=${encodeURIComponent(p.id)}"><img src="${esc(p.image)}" alt=""><div><small>${esc(p.brand)} · ${esc(p.category)}</small><strong>${esc(p.name)}</strong><span>${money(p.price)}</span></div></a>`).join(''):'<p>NESSUN FIND. PROVA UN ALTRO TERMINE.</p>'}
function renderCart(){const b=$('#cart');if(!b)return;const total=cart.reduce((t,x)=>t+(products.find(p=>p.id===x.id)?.price||0)*x.qty,0);b.innerHTML=`<div class="carttop"><span>YOUR FIND</span><button type="button" onclick="closeCart()">CLOSE ×</button></div><div class="cartlist">${cart.length?cart.map((x,i)=>{const p=products.find(p=>p.id===x.id);return p?`<div class="cartitem"><img src="${esc(p.image)}"><div><small>${esc(p.brand)}</small><strong>${esc(p.name)}</strong><span>${esc(x.size)} · ${x.qty} × ${money(p.price)}</span><button type="button" onclick="removeItem(${i})" style="margin-top:10px;border:0;background:none;font:8px 'DM Mono'">REMOVE</button></div></div>`:''}).join(''):'<p style="font:9px DM Mono;color:#777">NON HAI ANCORA TROVATO NULLA.</p>'}</div><div class="cartbottom"><div class="carttotal"><span>SUBTOTAL</span><strong>${money(total)}</strong></div><a class="btn dark" href="checkout.html">I’LL TAKE IT ↗</a></div>`}
function removeItem(i){cart.splice(i,1);persist()}window.removeItem=removeItem;
function filtered(){const q=new URLSearchParams(location.search);let l=[...products],c=q.get('cat'),b=q.get('brand'),badge=q.get('badge'),u=q.get('under'),term=q.get('q');if(c)l=l.filter(p=>p.category===c);if(b)l=l.filter(p=>p.brand===b);if(badge)l=l.filter(p=>p.badge===badge);if(u)l=l.filter(p=>Number(p.price)<Number(u));if(term){term=term.toLowerCase();l=l.filter(p=>[p.name,p.brand,p.category,p.id].join(' ').toLowerCase().includes(term))}return l}
function renderHome(){const l=products.slice(0,4);$('#featured').innerHTML=l.map(card).join('');$('#featuredCount').textContent=String(l.length).padStart(2,'0')+' PIECES / CURATED';$('#brandWall').innerHTML=[...new Set(products.map(p=>p.brand))].map((b,i)=>`<a href="shop.html?brand=${encodeURIComponent(b)}"><span>${String(i+1).padStart(2,'0')}</span><b>${esc(b)}</b><i>↗</i></a>`).join('');const f=$('#newsletterForm');if(f)f.onsubmit=e=>{e.preventDefault();$('#newsletterMsg').textContent='FIND LIST DEMO — collegare provider email prima del go-live.';f.reset()}}
function renderShop(){const l=filtered();$('#products').innerHTML=l.map(card).join('')||'<p style="grid-column:1/-1;font:9px DM Mono;color:#777">NESSUN FIND.</p>';$('#resultCount').textContent=String(l.length).padStart(2,'0')+' PIECES';const q=new URLSearchParams(location.search);$('#activeLabel').textContent=(q.get('cat')||q.get('brand')||q.get('badge')||'ALL STOCK').toUpperCase();$$('.filter').forEach(b=>{b.classList.toggle('active',b.dataset.cat===(q.get('cat')||''));b.onclick=()=>location.href=b.dataset.cat?'shop.html?cat='+encodeURIComponent(b.dataset.cat):'shop.html'})}
function renderProduct(){const id=new URLSearchParams(location.search).get('id'),p=products.find(x=>x.id===id)||products[0];if(!p)return;document.title=p.name+' — STOCK & FOUND 88';$('#product').innerHTML=`<div class="product-image"><img src="${esc(p.image)}" alt="${esc(p.name)}"></div><div class="product-info"><div class="eyebrow">${esc(p.brand)} · ${esc(p.category)} · ${esc(p.id)}</div><h1>${esc(p.name)}</h1><div class="price">${money(p.price)} ${p.compareAt?'<del>'+money(p.compareAt)+'</del>':''}</div><p>${esc(p.description)}</p><div class="eyebrow">PICK YOUR SIZE</div><div class="sizes">${p.sizes.map((s,i)=>`<button type="button" class="size ${i?'':'active'}" data-size="${esc(s)}">${esc(s)}</button>`).join('')}</div><button type="button" class="add" id="add">I’LL TAKE IT ↗</button><div class="note">ALMOST GONE / SELECTED PIECE<br>Se lo trovi, non è detto che lo ritrovi.</div><div style="margin-top:18px;font:8px/1.5 'DM Mono';color:#777">DEMO CATALOG · <a href="${esc(p.reference_url)}" target="_blank">official reference ↗</a></div></div>`;$$('.size').forEach(b=>b.onclick=()=>{$$('.size').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$('#add').onclick=()=>{const s=$('.size.active')?.dataset.size||p.sizes[0],x=cart.find(i=>i.id===p.id&&i.size===s);x?x.qty++:cart.push({id:p.id,size:s,qty:1});persist();openCart()}}
function renderFinder(){const f=$('#finderForm');if(!f)return;f.onsubmit=e=>{e.preventDefault();const p=[];if($('#finderCat').value)p.push('cat='+encodeURIComponent($('#finderCat').value));if($('#finderPrice').value)p.push('under='+encodeURIComponent($('#finderPrice').value));if($('#finderQuery').value.trim())p.push('q='+encodeURIComponent($('#finderQuery').value.trim()));$('#finderResult').textContent='OPENING THE HUNT…';setTimeout(()=>location.href='shop.html'+(p.length?'?'+p.join('&'):''),180)}}
function renderCheckout(){const f=$('#checkoutForm');if(!f)return;f.onsubmit=e=>{e.preventDefault();f.innerHTML='<div class="eyebrow">FIND RECEIVED</div><h2 style="font-size:52px;line-height:.8">IL TUO<br>FIND È<br>QUASI TUO.</h2><p style="color:#77736d">Demo checkout: pagamenti, ordini, stock ed email vanno collegati prima del go-live.</p>';cart=[];persist()}}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeCart()});document.addEventListener('DOMContentLoaded',async()=>{try{await load();mountHeader();mountFooter();renderCart();const page=document.body.dataset.page;if(page==='home')renderHome();if(page==='shop')renderShop();if(page==='product')renderProduct();if(page==='finder')renderFinder();if(page==='checkout')renderCheckout();$('#overlay')?.addEventListener('click',closeCart)}catch(e){console.error(e)}});
